// <auto-generated />
using System;
using BookStoreManagement.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace BookStoreManagement.Data.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20230530130500_Initial")]
    partial class Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.11")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("BookStoreManagement.Core.Entities.Author", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:IdentityIncrement", 1)
                        .HasAnnotation("SqlServer:IdentitySeed", 1)
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("Authors");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Jimmy Chin is an Academy Award-winning filmmaker, National Geographic photographer, and professional mountain sports athlete. He has led or participated in cutting-edge expeditions around the world for over twenty years, including significant first ascents on all seven continents, and his photographs have graced the covers of National Geographic Magazine and the New York Times Magazine",
                            Name = "Jimmy Chin"
                        },
                        new
                        {
                            Id = 2,
                            Description = "Joanna Ho is passionate about equity in books and education. She has been an English teacher, a dean, and a teacher professional development mastermind. She is currently the vice principal of a high school in the San Francisco Bay Area. Homemade chocolate chip cookies, outdoor adventures, and dance parties with her kids make Joanna's eyes crinkle into crescent moons. Her books for young readers include Eyes That Kiss in the Corners. Visit her at www.joannahowrites.com and @JoannaHoWrites.",
                            Name = "Joanna Ho"
                        },
                        new
                        {
                            Id = 3,
                            Description = "Stephen King is the author of more than sixty books, all of them worldwide bestsellers. His recent work includes Billy Summers, If It Bleeds, The Institute, Elevation, The Outsider, Sleeping Beauties (cowritten with his son Owen King), and the Bill Hodges trilogy: End of Watch, Finders Keepers, and Mr. Mercedes (an Edgar Award winner for Best Novel and a television series streaming on Peacock)",
                            Name = "Stephen King"
                        },
                        new
                        {
                            Id = 4,
                            Description = "Sanmao, born Chen Mao Ping, was a novelist, writer, educator and translator. Born in China in 1943, she grew up in Taiwan. She studied in Taiwan, Spain and Germany before moving to the Sahara desert with her Spanish husband, a scuba diver and underwater engineer. In 1976, she gained fame with the publication of her first book, Stories of the Sahara. Her husband died while diving in 1979, and Sanmao returned to Taiwan the following year.",
                            Name = "Sanmao"
                        },
                        new
                        {
                            Id = 5,
                            Description = "Kathe Koja writes novels and short fiction, and creates and produces immersive fiction performances, both solo and with a rotating ensemble of artists.",
                            Name = "Kathe Koja"
                        },
                        new
                        {
                            Id = 6,
                            Description = "Rebecca Roanhorse is the New York Times bestselling author of Trail of Lightning, Storm of Locusts, Black Sun, and Star Wars: Resistance Reborn. She has won the Nebula, Hugo, and Locus Awards for her fiction, and was the recipient of the 2018 Astounding (formerly Campbell) Award for Best New Writer. The next book in her Between Earth and Sky series, Fevered Star, is out in March 2022. She lives in New Mexico with her family.",
                            Name = "Rebecca Roanhorse"
                        },
                        new
                        {
                            Id = 7,
                            Description = "Nathaniel Rich is the author of the novels King Zeno, Odds Against Tomorrow, and The Mayor's Tongue. He is a writer at large for The New York Times Magazine and a regular contributor to The Atlantic and The New York Review of Books. He lives in New Orleans.",
                            Name = "Nathaniel Rich"
                        },
                        new
                        {
                            Id = 8,
                            Description = "Kate Pentecost was born and raised on the Texas/Louisiana state line, where there are more churches, pine trees, and alligators than anything else. She is a stalwart advocate of the weird, and has an MFA in Writing for Children and Young Adults from Vermont College of Fine Arts. Elysium Girls is her debut.",
                            Name = "Kate Pentecost"
                        },
                        new
                        {
                            Id = 9,
                            Description = "aura Roberts writes about sex, travel, writing, and ninjas - though not necessarily in that order. As the author of the 'V for Vixen' sex column, Laura began her career chronicling Montrealer's sexcapades, which are collected together in her book of essays, The Vixen Files. Blurring the lines between fact and fiction, she's also penned Confessions of a 3-Day Novelist, Ninjas of the 512, parts one and two of her serial novel, Naked Montreal, and a wide assortment of erotic Quickies",
                            Name = "Laura Roberts"
                        },
                        new
                        {
                            Id = 10,
                            Description = "Margaret Weis published their first novel in the Dragonlance Chronicles, Dragons of Autumn Twilight, in 1984. Over twenty years later, they are going strong as partners--with over thirty novels as collaborators--and have published over a hundred books, including novels, collections of short stories, role-playing games, and other game products alone or with other co-authors",
                            Name = "Margaret Weis"
                        });
                });

            modelBuilder.Entity("BookStoreManagement.Core.Entities.Book", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:IdentityIncrement", 1)
                        .HasAnnotation("SqlServer:IdentitySeed", 1)
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("AuthorId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValue(new DateTime(2023, 5, 30, 13, 4, 59, 841, DateTimeKind.Utc).AddTicks(98));

                    b.Property<bool>("IsActice")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("PhotoPublicId")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("PhotoUrl")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<decimal>("Price")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("Money")
                        .HasDefaultValue(0m);

                    b.Property<int?>("PublisherId")
                        .HasColumnType("int");

                    b.Property<int>("Quantity")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<string>("Summary")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("AuthorId");

                    b.HasIndex("PublisherId");

                    b.ToTable("Books");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AuthorId = 9,
                            CreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsActice = true,
                            PhotoPublicId = "BookStore/bookcovers/san_dghfys",
                            PhotoUrl = "https://res.cloudinary.com/dglgzh0aj/image/upload/v1634554755/BookStore/bookcovers/san_dghfys.jpg",
                            Price = 15.85m,
                            PublisherId = 4,
                            Quantity = 20,
                            Summary = "<p>Tired of the same old guidebooks? Learn where to go and what to do from a local! This alphabetical city guide looks at San Diego - and tourism - from a whole new angle, letting readers browse the city at their own pace. Learn about... * Local favorites * Tourist attractions * Cultural oddities * And enjoy unique trivia you just won't get from the other guys! Whether you're a first-time visitor or a life-long resident, San Diego from A to Z will surprise and delight you with plenty of facts, figures and personal experiences from author Laura Roberts. Explore alphabetically as you tour America's Finest City, starting at the Birch Aquarium and ending with Spanish phrases that begin with the letter Z. Learn more about San Diego landmarks, eateries, bars, museums, bookstores, neighborhoods, cultural oddities and much more. A must-have for the discerning traveler or seasoned flâneur. Find out what you've been missing in San Diego and order your copy today.</p>",
                            Title = "San Diego from A to Z: An Alphabetical Guide"
                        },
                        new
                        {
                            Id = 2,
                            AuthorId = 8,
                            CreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsActice = true,
                            PhotoPublicId = "BookStore/bookcovers/elisium_nudddg",
                            PhotoUrl = "https://res.cloudinary.com/dglgzh0aj/image/upload/v1634555234/BookStore/bookcovers/elisium_nudddg.jpg",
                            Price = 27.55m,
                            PublisherId = 3,
                            Quantity = 50,
                            Summary = "<p>A lush, dazzlingly original young adult fantasy about an epic clash of witches, gods, and demons. Elysium, Oklahoma, is a town like any other. Respectable. God-fearing. Praying for an end to the Dust Bowl.Until the day the people of Elysium are chosen by two sisters: Life and Death.And the Sisters like to gamble against each other with things like time, and space, and human lives.Elysium is to become the gameboard in a ruthless competition between the goddesses.The Dust Soldiers will return in ten years' time, and if the people of Elysium have not proved themselves worthy, all will be slain. Nearly ten years later, seventeen-year - old Sal Wilkinson is called upon to lead Elysium as it prepares for the end of the game.But then an outsider named Asa arrives at Elysium's gates with nothing more than a sharp smile and a bag of magic tricks, and they trigger a terrible accident that gets both Sal and Asa exiled into the brutal Desert of Dust and Steel. There Sal and Asa stumble upon a gang of girls headed by another exile: a young witch everyone in Elysium believes to be dead. As the apocalypse looms, they must do more than simply tip the scales in Elysium's favor-only by reinventing the rules can they beat Life and Death at their own game in this exciting fantasy debut.</p>",
                            Title = "Elysium Girls"
                        },
                        new
                        {
                            Id = 3,
                            AuthorId = 6,
                            CreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsActice = true,
                            PhotoPublicId = "BookStore/bookcovers/71ZMYPkoNLL_y2she6",
                            PhotoUrl = "https://res.cloudinary.com/dglgzh0aj/image/upload/v1634555700/BookStore/bookcovers/71ZMYPkoNLL_y2she6.jpg",
                            Price = 25.75m,
                            PublisherId = 1,
                            Quantity = 30,
                            Summary = "<p>In the holy city of Tova, the winter solstice is usually a time for celebration and renewal, but this year it coincides with a solar eclipse, a rare celestial event proscribed by the Sun Priest as an unbalancing of the world. Meanwhile, a ship launches from a distant city bound for Tova and set to arrive on the solstice. The captain of the ship, Xiala, is a disgraced Teek whose song can calm the waters around her as easily as it can warp a man's mind. Her ship carries one passenger. Described as harmless, the passenger, Serapio, is a young man, blind, scarred, and cloaked in destiny. As Xiala well knows, when a man is described as harmless, he usually ends up being a villain. Crafted with unforgettable characters, Rebecca Roanhorse has created an epic adventure exploring the decadence of power amidst the weight of history and the struggle of individuals swimming against the confines of society and their broken pasts in the most original series debut of the decade.</p>",
                            Title = "Black Sun, 1"
                        },
                        new
                        {
                            Id = 4,
                            AuthorId = 3,
                            CreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsActice = true,
                            PhotoPublicId = "BookStore/bookcovers/9780345806789_p0_v2_s1200x630_a9ruho",
                            PhotoUrl = "https://res.cloudinary.com/dglgzh0aj/image/upload/v1634556141/BookStore/bookcovers/9780345806789_p0_v2_s1200x630_a9ruho.jpg",
                            Price = 36.80m,
                            PublisherId = 3,
                            Quantity = 55,
                            Summary = "<p>Jack Torrance's new job at the Overlook Hotel is the perfect chance for a fresh start. As the off-season caretaker at the atmospheric old hotel, he'll have plenty of time to spend reconnecting with his family and working on his writing. But as the harsh winter weather sets in, the idyllic location feels ever more remote . . . and more sinister. And the only one to notice the strange and terrible forces gathering around the Overlook is Danny Torrance, a uniquely gifted five-year-old.</p>",
                            Title = "The Shining"
                        },
                        new
                        {
                            Id = 5,
                            AuthorId = 3,
                            CreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsActice = true,
                            PhotoPublicId = "BookStore/bookcovers/715w3hVk-dL_hvnmbd",
                            PhotoUrl = "https://res.cloudinary.com/dglgzh0aj/image/upload/v1634556342/BookStore/bookcovers/715w3hVk-dL_hvnmbd.jpg",
                            Price = 28.20m,
                            PublisherId = 1,
                            Quantity = 45,
                            Summary = "<p>An impressive work of mythic magnitude that may turn out to be Stephen King's greatest literary achievement (The Atlanta Journal-Constitution), The Gunslinger</p>",
                            Title = "The Dark Tower I, 1: The Gunslinger"
                        },
                        new
                        {
                            Id = 6,
                            AuthorId = 10,
                            CreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsActice = true,
                            PhotoPublicId = "BookStore/bookcovers/81Mtr5rXctL_bpihhq",
                            PhotoUrl = "https://res.cloudinary.com/dglgzh0aj/image/upload/v1634556692/BookStore/bookcovers/81Mtr5rXctL_bpihhq.jpg",
                            Price = 19.99m,
                            PublisherId = 4,
                            Quantity = 25,
                            Summary = "<p>Once merely creatures of legend, the dragons have returned to Krynn. But with their arrival comes the departure of the old gods--and all healing magic. As war threatens to engulf the land, lifelong friends reunite for an adventure that will change their lives and shape their world forever... When Tanis, Sturm, Caramon, Raistlin, Flint, and Tasslehoff see a woman use a blue crystal staff to heal a villager, they wonder if it's a sign the gods have not abandoned them after all. Fueled by this glimmer of hope, the Companions band together to uncover the truth behind the gods' absence--though they aren't the only ones with an interest in the staff. The Seekers, a new religious order, wants the artifact for their own ends, believing it will help them replace the gods and overtake the continent of Ansalon. Now, the Companions must assume the unlikely roles of heroes if they hope to prevent the staff from falling into the hands of darkness.</p>",
                            Title = "Dragons of Autumn Twilight"
                        });
                });

            modelBuilder.Entity("BookStoreManagement.Core.Entities.BookCategories", b =>
                {
                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<int>("BookId")
                        .HasColumnType("int");

                    b.HasKey("CategoryId", "BookId");

                    b.HasIndex("BookId");

                    b.ToTable("BookCategories");

                    b.HasData(
                        new
                        {
                            CategoryId = 10,
                            BookId = 1
                        },
                        new
                        {
                            CategoryId = 9,
                            BookId = 2
                        },
                        new
                        {
                            CategoryId = 8,
                            BookId = 3
                        },
                        new
                        {
                            CategoryId = 6,
                            BookId = 4
                        },
                        new
                        {
                            CategoryId = 6,
                            BookId = 5
                        },
                        new
                        {
                            CategoryId = 4,
                            BookId = 6
                        });
                });

            modelBuilder.Entity("BookStoreManagement.Core.Entities.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:IdentityIncrement", 1)
                        .HasAnnotation("SqlServer:IdentitySeed", 1)
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Arts & Photography"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Children's Books"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Comics & Graphic Novels"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Fantasy"
                        },
                        new
                        {
                            Id = 5,
                            Name = "History"
                        },
                        new
                        {
                            Id = 6,
                            Name = "Horror"
                        },
                        new
                        {
                            Id = 7,
                            Name = "Science Fiction"
                        },
                        new
                        {
                            Id = 8,
                            Name = "Science & Technology"
                        },
                        new
                        {
                            Id = 9,
                            Name = "Teen & Young Adult"
                        },
                        new
                        {
                            Id = 10,
                            Name = "Travel"
                        });
                });

            modelBuilder.Entity("BookStoreManagement.Core.Entities.Comment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:IdentityIncrement", 1)
                        .HasAnnotation("SqlServer:IdentitySeed", 1)
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("AnonymousName")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int?>("BookId")
                        .HasColumnType("int");

                    b.Property<string>("Content")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime>("CreatedDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValue(new DateTime(2023, 5, 30, 13, 4, 59, 845, DateTimeKind.Utc).AddTicks(9490));

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("BookId");

                    b.HasIndex("UserId");

                    b.ToTable("Comments");
                });

            modelBuilder.Entity("BookStoreManagement.Core.Entities.Publisher", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:IdentityIncrement", 1)
                        .HasAnnotation("SqlServer:IdentitySeed", 1)
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("Publishers");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Launched in 2017, Hanover Square Press aims to publish compelling, original fiction and narrative nonfiction—the kind of books that keep you up all night reading and that you want to talk about the next morning. The imprint draws its name from the square that was once known as “Printing House Square” for the American printers, publishers, and booksellers who thrived there in the 1700s and early 1800s.",
                            Name = "Hanover Square Press"
                        },
                        new
                        {
                            Id = 2,
                            Description = "Grand Central Publishing, formerly Warner Books, came into existence in 1970 when Warner Communications acquired the Paperback Library, subsequently publishing paperback reprints editions of such bestsellers as Harper Lee's To Kill A Mockingbird and Umberto Eco's The Name Of The Rose. Today Grand Central Publishing reaches a diverse audience through hardcover, trade paperback and mass market imprints that cater to every kind of reader.",
                            Name = "Grand Central Publishing"
                        },
                        new
                        {
                            Id = 3,
                            Description = "Copper Canyon Press is a nonprofit, independent poetry publisher based in Port Townsend, WA. We believe poetry is vital to language and living. Since 1972, Copper Canyon has published extraordinary poetry from around the world to engage the imaginations and intellects of readers.",
                            Name = "Copper Canyon Press"
                        },
                        new
                        {
                            Id = 4,
                            Description = "On-Demand Publishing, LLC, doing business as CreateSpace, is a self-publishing service owned by Amazon. The company was founded in 2000 in South Carolina as BookSurge and was acquired by Amazon in 2005.",
                            Name = "Createspace Independent Publishing Platform"
                        });
                });

            modelBuilder.Entity("BookStoreManagement.Core.Entities.RefreshToken", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("Expires")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("Revoked")
                        .HasColumnType("datetime2");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("RefreshTokens");
                });

            modelBuilder.Entity("BookStoreManagement.Core.Entities.Role", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ConcurrencyStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("NormalizedName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Roles");

                    b.HasData(
                        new
                        {
                            Id = new Guid("69bd714f-9576-45ba-b5b7-f00649be00de"),
                            ConcurrencyStamp = "1f6ca8c7-1f6c-4233-b471-d96df02bd5c9",
                            Description = "Site Owner has all right of website",
                            Name = "SiteOwner"
                        },
                        new
                        {
                            Id = new Guid("8d04dce2-969a-435d-bba4-df3f325983dc"),
                            ConcurrencyStamp = "f2a01991-4b84-4df5-8139-6046e55a51ef",
                            Description = "Normal User is restricted some rights",
                            Name = "NormalUser"
                        });
                });

            modelBuilder.Entity("BookStoreManagement.Core.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("Avatar")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<string>("AvatarPublicId")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("ConcurrencyStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Status")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = new Guid("9977fad2-d8b9-4ac4-a73d-14cbf64ed65c"),
                            AccessFailedCount = 0,
                            Avatar = "https://img.freepik.com/free-vector/flat-design-library-logo-template_23-2149325326.jpg?w=2000",
                            AvatarPublicId = "BookStore/users/flat-design-library-logo-template_23-2149325326.jpg?w=2000",
                            ConcurrencyStamp = "88554467-4552-4956-b6dc-b2ba681890f9",
                            DisplayName = "Hà Hải Long",
                            Email = "hailongsn99@gmail.com",
                            EmailConfirmed = true,
                            LockoutEnabled = false,
                            PasswordHash = "AQAAAAEAACcQAAAAEF2VIoLU2t5VbHOZvIClem25wb4G+ITkbSkmFU2lrpAp1sZWJ0/RLhaqKgK532Qv8Q==",
                            PhoneNumber = "0375274267",
                            PhoneNumberConfirmed = true,
                            SecurityStamp = "",
                            Status = false,
                            TwoFactorEnabled = false,
                            UserName = "hailongsn99@gmail.com"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<System.Guid>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.ToTable("RoleClaims");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<System.Guid>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.ToTable("UserClaims");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<System.Guid>", b =>
                {
                    b.Property<Guid>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId");

                    b.ToTable("UserLogins");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<System.Guid>", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("UserId", "RoleId");

                    b.ToTable("UserRoles");

                    b.HasData(
                        new
                        {
                            UserId = new Guid("9977fad2-d8b9-4ac4-a73d-14cbf64ed65c"),
                            RoleId = new Guid("69bd714f-9576-45ba-b5b7-f00649be00de")
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<System.Guid>", b =>
                {
                    b.Property<Guid>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId");

                    b.ToTable("UserTokens");
                });

            modelBuilder.Entity("BookStoreManagement.Core.Entities.Book", b =>
                {
                    b.HasOne("BookStoreManagement.Core.Entities.Author", "Author")
                        .WithMany("Books")
                        .HasForeignKey("AuthorId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("BookStoreManagement.Core.Entities.Publisher", "Publisher")
                        .WithMany("Books")
                        .HasForeignKey("PublisherId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.Navigation("Author");

                    b.Navigation("Publisher");
                });

            modelBuilder.Entity("BookStoreManagement.Core.Entities.BookCategories", b =>
                {
                    b.HasOne("BookStoreManagement.Core.Entities.Book", "Book")
                        .WithMany("BookCategories")
                        .HasForeignKey("BookId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BookStoreManagement.Core.Entities.Category", "Category")
                        .WithMany("BookCategories")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Book");

                    b.Navigation("Category");
                });

            modelBuilder.Entity("BookStoreManagement.Core.Entities.Comment", b =>
                {
                    b.HasOne("BookStoreManagement.Core.Entities.Book", "Book")
                        .WithMany("Comments")
                        .HasForeignKey("BookId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("BookStoreManagement.Core.Entities.User", "User")
                        .WithMany("Comments")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.Navigation("Book");

                    b.Navigation("User");
                });

            modelBuilder.Entity("BookStoreManagement.Core.Entities.RefreshToken", b =>
                {
                    b.HasOne("BookStoreManagement.Core.Entities.User", "User")
                        .WithMany("RefreshTokens")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.Navigation("User");
                });

            modelBuilder.Entity("BookStoreManagement.Core.Entities.Author", b =>
                {
                    b.Navigation("Books");
                });

            modelBuilder.Entity("BookStoreManagement.Core.Entities.Book", b =>
                {
                    b.Navigation("BookCategories");

                    b.Navigation("Comments");
                });

            modelBuilder.Entity("BookStoreManagement.Core.Entities.Category", b =>
                {
                    b.Navigation("BookCategories");
                });

            modelBuilder.Entity("BookStoreManagement.Core.Entities.Publisher", b =>
                {
                    b.Navigation("Books");
                });

            modelBuilder.Entity("BookStoreManagement.Core.Entities.User", b =>
                {
                    b.Navigation("Comments");

                    b.Navigation("RefreshTokens");
                });
#pragma warning restore 612, 618
        }
    }
}
